//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsSiguemeQ.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entidad()
        {
            this.Entidad_Servicio = new HashSet<Entidad_Servicio>();
        }
    
        public long idEntidad { get; set; }
        public Nullable<long> idEntidadRelacionada { get; set; }
        public string idTipoIdentificacion { get; set; }
        public string numeroIdentificacion { get; set; }
        public int digitoVerificacion { get; set; }
        public string codigoHabilitacion { get; set; }
        public string nombreEntidad { get; set; }
        public int idNaturalezaJuridica { get; set; }
        public string correoElectronico { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public Nullable<bool> direccionNoUrbana { get; set; }
        public Nullable<int> idLocalidadDireccion { get; set; }
        public string idBarrioDireccion { get; set; }
        public Nullable<int> idUpzDireccion { get; set; }
        public Nullable<System.DateTime> fechaInscripcionRUH { get; set; }
        public Nullable<int> idTipoPrestador { get; set; }
        public Nullable<int> idTipoNitComun { get; set; }
        public System.DateTime fechaCreado { get; set; }
        public System.DateTime fechaActualizado { get; set; }
        public string usrCreado { get; set; }
        public string usrModificado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entidad_Servicio> Entidad_Servicio { get; set; }
    }
}
