//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsSiguemeQ.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Queja = new HashSet<Queja>();
            this.Queja1 = new HashSet<Queja>();
        }
    
        public long idPersona { get; set; }
        public string idTipoIdentificacion { get; set; }
        public string numeroIdentificacion { get; set; }
        public Nullable<int> digitoVerificacion { get; set; }
        public string primerNombre { get; set; }
        public string segundoNombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string nombresApellidos { get; set; }
        public string direccion { get; set; }
        public Nullable<int> idTipoDireccion { get; set; }
        public Nullable<int> idLocalidad { get; set; }
        public string idBarrio { get; set; }
        public int idUpz { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string correoElectronico { get; set; }
        public System.DateTime fechaCreado { get; set; }
        public Nullable<System.DateTime> fechaModificado { get; set; }
        public string usrCreado { get; set; }
        public string usrModificado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Queja> Queja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Queja> Queja1 { get; set; }
    }
}
