//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsSiguemeQ.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Queja()
        {
            this.Visita = new HashSet<Visita>();
        }
    
        public long idQueja { get; set; }
        public Nullable<int> idTipoSolicitud { get; set; }
        public string numeroRadicadoQueja { get; set; }
        public Nullable<System.DateTime> fechaRadicadoQueja { get; set; }
        public Nullable<System.DateTime> fechaLimiteRespuesta { get; set; }
        public Nullable<int> idEntidadRemitente { get; set; }
        public string numeroRadicadoAtencionUsuario { get; set; }
        public Nullable<int> idTipoRecepcionQueja { get; set; }
        public Nullable<long> idPersonaQuejoso { get; set; }
        public Nullable<long> idPersonaAfectado { get; set; }
        public Nullable<long> idEntidadServicioInvolucrada { get; set; }
        public string motivoQueja { get; set; }
        public string radicadosRelacionados { get; set; }
        public Nullable<int> idPalabrasClaves { get; set; }
        public int idCaracteristicasEspeciales { get; set; }
        public Nullable<int> idTipoDireccionamiento { get; set; }
        public Nullable<int> idGrupoEntrega { get; set; }
        public Nullable<int> foliosEntrega { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public Nullable<int> idEstadoQueja { get; set; }
        public Nullable<System.DateTime> fechaCreado { get; set; }
        public Nullable<System.DateTime> fechaActualizado { get; set; }
        public string usrCreado { get; set; }
        public string usrModificado { get; set; }
    
        public virtual Entidad_Servicio Entidad_Servicio { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Persona Persona1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visita> Visita { get; set; }
    }
}
