//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsSiguemeQ.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita
    {
        public long idVisita { get; set; }
        public Nullable<long> idQueja { get; set; }
        public Nullable<System.DateTime> fechaVisita { get; set; }
        public Nullable<int> idEstadoVisita { get; set; }
        public Nullable<System.DateTime> fechaEntregaVisita { get; set; }
        public Nullable<System.DateTime> fechaReciboVisita { get; set; }
        public Nullable<int> idCoordinador { get; set; }
        public Nullable<int> foliosResultadoVisita { get; set; }
        public string anexosResultadoVisita { get; set; }
        public Nullable<int> idResultadoVisita { get; set; }
        public Nullable<int> idTipoMedida { get; set; }
        public Nullable<int> idImposicionMedidaREPS { get; set; }
    
        public virtual Queja Queja { get; set; }
    }
}
